type = "service_account"
project_id = "gen-ai-rajan-labs"
private_key_id = "a45542099d9ecf256994b166093b3a862d7ccdcf"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDEarHJsquq4U4d
+NJCcjJ428SZ2YywacDO+jVLGKpo9Eq8qFBNhmUBqE6XwGYR937leGaji1etyn7i
60j6ayosQ4iGY+wkuNmUdrpna/Yq7LidWHE0ykCNuK6r58khO0mgLEQTxJYrnZPt
rE/i8QPIQci2LFT2ACHVbPNgBi7b3gyaxsx7FUmD1Ygu6mfJxgkZPElrmTfOqz5/
btgbxgWN/b4Q5uTNltbkOWq1KLB+gwRxExIiagGownCznNFeGUKB1YdRxM/4lAME
tRO3uYgGISwlVTFblUCdkzuAQNgyzmTlWIgEgTZAQz3sDQT0b7xiHApQlq0CyWI6
mtWOLJxVAgMBAAECggEALESJtlY094nY88tZBA29z1xkpnIQEdB72oosybSQ75+j
WnqqwpY4HJQExpHfz0vTBz/IDjMA+1PInjb+FyZg9mHwGq3Zknsw2pOZtmZwMENy
5k+BEC9HNkm54FeYjotQsC9Z1oS3fbQBm4764ECGpDMjW9+I9HqaJYJtJaavF/FB
4vHsckmxGZT9TcDQ1JPQpd96/siVZY2G0/v7Fn7lyO0XJXUCP8kqBUlCJnCKodiu
PUr9BLNjj9Mav4guVSKbSeJPFUflHyIB3s14fRck0pd37wj2Yg6wQNNBAofS7h6V
npVZgawZ6h/T/RNkiOohNGNbVSidVhcB/mXnVmN2gQKBgQDvypSjVcAeaayKyrI7
KAA+LjILS52qfGDgSM5QO5mQoPx2VMEDRlzL6a7wfSxnX1WYnTfx2JnSi1QBemDt
cy8aJs6GPBRn0i2pqfjfvrRVx1tlDZNrGKVVW8n+4OedxBy2odSxDcioHJrFANtL
DUKFtnEtUAY6RaqCzkksKvFFQQKBgQDRsYxA53Si4vB2x44I6+g1tHxd0f8i+Iwr
oVV5VazWZzSQWsQtg7xht3zj7ku7yoydZ9/ngYT1lAWKd4RkSgP7wJKsaI/KPTTO
UCF+clUN4ziBYlIAuLBA9DwQKU3inyCtqbIHCrqJyPt7MxSC7gUUYRQq8XgY1/Yv
TqYOFKBuFQKBgGa65nUXbqhY44fOkQ8Q8xGwntYB/jkk8igEaQcskXzJy38yjkJF
6cmegskbB2P+DuDEMkyVXEk8UbAUauQvnbVZfM87fA6Cl/eBD1NkE0RQlVI0v7x5
IZPxMBfW6MPJWffQWxvDaPzEzHWsCUcdFivM3q3oA9MBN6y0jdqzRwxBAoGBAIwF
lPQaGiZSh+Oo6U1Hye1isdEsUsQVV/QibSLydNFOZSknkuwZlYdisQC6tNOXM0JA
hKDgOdqKlxCZMkyNqA9JzidWQv321PYXR+ZZjjYRzj+HWd6ldPxKmnjoO9viCj4s
nHZbUaiEDnl76GxtZ/LtyDvMtjdQrlF0oSmx2FbpAoGBAIPPSzA7YAvgP/szV/53
VtrB0sshwQEJGkIckmYaqVtEe70fRWldIa8+bABNVIZMEUHgFM9GibBm8zHsmEMM
mwHrJ/d53DPI+j0f3kLlfLPX3i8RyAdOnRqT8SXyKPQ6Y3euM7s5sGhdlntTdPsq
mlZsZEWqLi8Rxq9EMPuOpKMH
-----END PRIVATE KEY-----
"""
client_email = "streamlit-gcs-access@gen-ai-rajan-labs.iam.gserviceaccount.com"
client_id = "103558448937815310638"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-gcs-access%40gen-ai-rajan-labs.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
